#!/bin/bash
#$ -l rmem=20G
#$ -l h_rt=48:00:00
#$ -m beas
#$ -M d.r.buxton@sheffield.ac.uk
#$ -o ~/logs/generate_striatum.out
#$ -e ~/logs/generate_striatum.err

# Set root directories
export LOGS_DIR="${HOME}/logs"

# Clear previous data
# rm ${LOGS_DIR}/*

# Run striatum generation script
module load apps/matlab

cd /home/ac1drb/MatLab/striatal_modelling

matlab -nodesktop -nosplash -r 'run generate_striatum.m'

